net/network-manager: refactor and overhaul
Overhaul the network-manager spell to be more complete and more correct.

There are still some options that aren't properly handled yet (e.g.
Qt-related options), but this should be an improvement over the existing
option handling.

diff --git a/net/network-manager/BUILD b/net/network-manager/BUILD
--- a/net/network-manager/BUILD
+++ b/net/network-manager/BUILD
@@ -1,26 +1,27 @@
-OPTS+=" tests=no"
-#OPTS+=" wext=false" #obsolete
-OPTS+=" qt=false"
-#OPTS+=" $NM_DOCS"
-if is_depends_enabled $SPELL systemd; then
-  OPTS+=" session_tracking=systemd"
-else
-  OPTS+=" session_tracking=elogind"
-  OPTS+=" suspend_resume=elogind"
-  OPTS+=" systemd_journal=false"
-  OPTS+=" systemdsystemunitdir=no"
+OPTS="$NM_TESTS $OPTS"
+#OPTS="wext=false $OPTS" #obsolete
+OPTS="qt=false $OPTS"
+OPTS="$NM_DOCS $OPTS"
+if ! is_depends_enabled "$SPELL" systemd; then
+  OPTS="systemd_journal=false $OPTS"
+  OPTS="systemdsystemunitdir=no $OPTS"
 fi &&
-if is_depends_enabled $SPELL iwd; then
-  config_wifi_backend_default=iwd
-else
-  config_wifi_backend_default=wpa_supplicant
+
+OPTS="config_wifi_backend_default=${DEFAULT_WIFI:-wpa_supplicant} $OPTS"
+OPTS="config_dhcp_default=${DEFAULT_DHCP:-internal} $OPTS"
+OPTS="$NM_CRYPTO $OPTS"
+OPTS="$LOGGING_BACKEND_OPT $OPTS"
+OPTS="$SUSPEND_RESUME_OPT $OPTS"
+OPTS="$SESSION_TRACKING_OPT $OPTS"
+
+if [ -n "$LINUX_FIRMWARE" ] ;then
+  OPTS="kernel_firmware_dir=${LINUX_FIRMWARE} $OPTS"
 fi &&
 
 # disable stripping
-LDFLAGS="${LDFLAGS//,-s/}" &&
-LDFLAGS="${LDFLAGS//-s,/}" &&
-LDFLAGS="${LDFLAGS// -s/}" &&
-LDFLAGS="${LDFLAGS//-s /}" &&
+# if stripping is enabled the build fails with "no symbols" errors
+LDFLAGS="${LDFLAGS//[, ]-s/}" &&
+LDFLAGS="${LDFLAGS//-s[, ]/}" &&
 LDFLAGS="${LDFLAGS//^-s$/}" &&
 
 default_build
