seamonkey: post-update fixes

diff --git a/http/seamonkey/mailnews.patch b/http/seamonkey/mailnews.patch
--- a/http/seamonkey/mailnews.patch
+++ b/http/seamonkey/mailnews.patch
@@ -1,10 +1,38 @@
---- mozilla/config/autoconf.mk.in.orig	2011-11-21 14:27:51.000000000 +0400
-+++ mozilla/config/autoconf.mk.in	2011-12-10 05:18:53.008294310 +0400
-@@ -125,7 +125,6 @@
- MOZ_LIBSTDCXX_HOST_VERSION=@MOZ_LIBSTDCXX_HOST_VERSION@
- INCREMENTAL_LINKER = @INCREMENTAL_LINKER@
- MACOSX_DEPLOYMENT_TARGET = @MACOSX_DEPLOYMENT_TARGET@
--MOZ_MAIL_NEWS	= @MOZ_MAIL_NEWS@
- ENABLE_TESTS	= @ENABLE_TESTS@
- IBMBIDI = @IBMBIDI@
- MOZ_UNIVERSALCHARDET = @MOZ_UNIVERSALCHARDET@
+--- mozilla/configure.orig	2011-11-21 14:29:14.000000000 +0400
++++ mozilla/configure	2011-12-10 16:04:46.337188291 +0400
+@@ -14788,6 +14788,7 @@
+ MOZ_FEEDS=1
+ MOZ_INSTALLER=1
+ MOZ_JSDEBUGGER=1
++MOZ_MAIL_NEWS=
+ MOZ_AUTH_EXTENSION=1
+ MOZ_OGG=1
+ MOZ_RAW=
+@@ -17714,8 +17715,17 @@
+ fi
+ 
+ 
+-
+-
++# Check whether --enable-mailnews or --disable-mailnews was given.
++if test "${enable_mailnews+set}" = set; then
++  enableval="$enable_mailnews"
++  if test "$enableval" = "no"; then
++    MOZ_MAIL_NEWS=
++  elif test "$enableval" = "yes"; then
++    MOZ_MAIL_NEWS=1 
++  else
++    { echo "configure: error: Option, mailnews, does not take an argument ($enableval)." 1>&2; exit 1; }
++  fi
++fi
+ 
+ 
+ # Check whether --enable-crypto or --disable-crypto was given.
+@@ -26203,6 +26213,7 @@
+ s%@MOZ_DFB@%$MOZ_DFB%g
+ s%@MOZ_X11@%$MOZ_X11%g
+ s%@MOZ_UI_LOCALE@%$MOZ_UI_LOCALE%g
++s%@MOZ_MAIL_NEWS@%$MOZ_MAIL_NEWS%g
+ s%@MOZ_OFFICIAL_BRANDING@%$MOZ_OFFICIAL_BRANDING%g
+ s%@MOZ_BRANDING_DIRECTORY@%$MOZ_BRANDING_DIRECTORY%g
+ s%@MOZ_DISTRIBUTION_ID@%$MOZ_DISTRIBUTION_ID%g
