sync ./collab/drupal from test

diff --git a/collab/drupal/INSTALL b/collab/drupal/INSTALL
--- a/collab/drupal/INSTALL
+++ b/collab/drupal/INSTALL
@@ -1,30 +1,47 @@
-install_www_files  ./  ${INSTALL_ROOT}${DRUPAL_INSTALL_PATH}/${SPELL}           &&
+install_www_files  ./  ${INSTALL_ROOT}${DRUPAL_INSTALL_PATH}/${SPELL}                                          &&
 
-if  [  "$DRUPAL_CREATEDB"  ==  "y"  ];  then
-  if  [  "$DRUPAL_MYSQL"  ==  "y"  ];  then
-    message  "${MESSAGE_COLOR}Creating MySQL database...${DEFAULT_COLOR}"
-    mysqladmin  create  drupal                           &&
-    echo  "GRANT ALL PRIVILEGES ON drupal.*              \
-          TO nobody@localhost IDENTIFIED BY 'password';  \
-          flush privileges;                              \
-          \q "  |  mysql  drupal                         &&
-    mysql  drupal  <  database/database.mysql  ||  true
-    #
-    # Return true as this will fail if the database already exists
-    #
-  fi  &&
+if  [  "${DRUPAL_INSTALLED}"  ==  "n"  ];  then
+  if  [  "${DRUPAL_CREATEDB}"  ==  "y"  ];  then
+    case  "${DRUPAL_DATABASE_ENGINE}"  in
+      mysql)
+        message  "${MESSAGE_COLOR}Creating MySQL database...${DEFAULT_COLOR}"
+        mysqladmin  create  ${DRUPAL_DATABASE_NAME}                                                            &&
+        echo  "GRANT ALL PRIVILEGES ON ${DRUPAL_DATABASE_NAME}.*                                               \
+              TO ${DRUPAL_DATABASE_USER}@${DRUPAL_DATABASE_HOST} IDENTIFIED BY '${DRUPAL_DATABASE_PASSWORD}';  \
+              flush privileges;                                                                                \
+              \q "  |  mysql  ${DRUPAL_DATABASE_NAME}                                                          &&
+        #
+        # Return true as this will fail if the database already exists
+        #
+        mysql  ${DRUPAL_DATABASE_NAME}  <  database/database.mysql  ||  true
+        ;;
 
-  if  [  "$DRUPAL_PGSQL"  ==  "y"  ];  then
-    message  "${MESSAGE_COLOR}Creating PostgreSQL database...${DEFAULT_COLOR}"
-    source  /etc/sysconfig/postgresql  &&
-    su  $USER  -c  "createdb  drupal"  &&
-    echo  "GRANT ALL PRIVILEGES ON drupal.*              \
-          TO nobody@localhost IDENTIFIED BY 'password';  \
-          flush privileges;                              \
-          \q "  |  su  $USER  -c  "psql  drupal"         &&
-    su  $USER  -c  "psql  drupal  -f  database/database.pgsql"  ||  true
-    #
-    # Return true as this will fail if the database already exists
-    #
-  fi
+      postgresql)
+        message  "${MESSAGE_COLOR}Creating PostgreSQL database...${DEFAULT_COLOR}"
+        source  /etc/sysconfig/postgresql                                                                      &&
+        su  ${USER}  -c  "createdb  ${DRUPAL_DATABASE_NAME}"                                                   &&
+        echo  "GRANT ALL PRIVILEGES ON ${DRUPAL_DATABASE_NAME}.*                                               \
+              TO ${DRUPAL_DATABASE_USER}@${DRUPAL_DATABASE_HOST} IDENTIFIED BY '${DRUPAL_DATABASE_PASSWORD}';  \
+              flush privileges;                                                                                \
+              \q "  |  su  ${USER}  -c  "psql  ${DRUPAL_DATABASE_NAME}"                                        &&
+        #
+        # Return true as this will fail if the database already exists
+        #
+        su  ${USER}  -c  "psql  ${DRUPAL_DATABASE_NAME}  -f  database/database.pgsql"  ||  true
+        ;;
+    esac
+  fi                                                                                                           &&
+
+  if  [  "${DRUPAL_CONFIGURE}"  ==  "y"  ];  then
+    # Update the sites/default/settings.php configuration file
+    # The database connection string
+    sedit  "s|username:password@localhost/database|${DRUPAL_DATABASE_USER}:${DRUPAL_DATABASE_PASSWORD}@${DRUPAL_DATABASE_HOST}/${DRUPAL_DATABASE_NAME}|"  ${INSTALL_ROOT}/${DRUPAL_INSTALL_PATH}/${SPELL}/sites/default/settings.php  &&
+
+    # The base URL string
+    sedit  "s|http://localhost|http://localhost/${SPELL}|"  ${INSTALL_ROOT}/${DRUPAL_INSTALL_PATH}/${SPELL}/sites/default/settings.php  &&
+
+    mkdir  ${INSTALL_ROOT}/${DRUPAL_INSTALL_PATH}/${SPELL}/files
+  fi                                                                                                           &&
+
+  chown  -R  www-data:www-data  ${INSTALL_ROOT}/${DRUPAL_INSTALL_PATH}/${SPELL}
 fi
