laptop-mode-tools: Cleanup strange characters in init script and cleanup provided install script to not muck with services

diff --git a/mobile/laptop-mode-tools/laptop-mode-tools-1_34.patch b/mobile/laptop-mode-tools/laptop-mode-tools-1_34.patch
--- a/mobile/laptop-mode-tools/laptop-mode-tools-1_34.patch
+++ b/mobile/laptop-mode-tools/laptop-mode-tools-1_34.patch
@@ -1,6 +1,6 @@
-diff -Naur laptop-mode-tools-1.34-orig/etc/init.d/laptop-mode laptop-mode-tools-1.34/etc/init.d/laptop-mode
---- laptop-mode-tools-1.34-orig/etc/init.d/laptop-mode	2007-05-13 09:59:51.000000000 -0600
-+++ laptop-mode-tools-1.34/etc/init.d/laptop-mode	2007-10-15 19:31:06.000000000 -0600
+diff -Naur laptop-mode-tools-1.34.orig/etc/init.d/laptop-mode laptop-mode-tools-1.34/etc/init.d/laptop-mode
+--- laptop-mode-tools-1.34.orig/etc/init.d/laptop-mode	2007-05-13 08:59:51.000000000 -0700
++++ laptop-mode-tools-1.34/etc/init.d/laptop-mode	2007-10-17 19:12:24.215585402 -0700
 @@ -6,9 +6,15 @@
  #
  # config:  /etc/laptop-mode/laptop-mode.conf
@@ -107,9 +107,9 @@ diff -Naur laptop-mode-tools-1.34-orig/etc/init.d/laptop-mode laptop-mode-tools-
 -exit 0
 +    $PROGRAM status
 +}
-diff -Naur laptop-mode-tools-1.34-orig/install.sh laptop-mode-tools-1.34/install.sh
---- laptop-mode-tools-1.34-orig/install.sh	2007-05-28 08:54:01.000000000 -0600
-+++ laptop-mode-tools-1.34/install.sh	2007-10-15 19:44:46.000000000 -0600
+diff -Naur laptop-mode-tools-1.34.orig/install.sh laptop-mode-tools-1.34/install.sh
+--- laptop-mode-tools-1.34.orig/install.sh	2007-05-28 07:54:01.000000000 -0700
++++ laptop-mode-tools-1.34/install.sh	2007-10-17 19:17:01.871227293 -0700
 @@ -2,43 +2,9 @@
  
  # If your distribution puts this in other locations, please adjust the values of
@@ -157,7 +157,25 @@ diff -Naur laptop-mode-tools-1.34-orig/install.sh laptop-mode-tools-1.34/install
  
  if [ "`whoami`" != "root" ] ; then
  	echo "You need to be root to install the laptop mode tools."
-@@ -202,31 +168,6 @@
+@@ -49,9 +15,6 @@
+ 	echo "Warning: the kernel you are running does not support laptop mode."
+ fi
+ 
+-echo 'Stopping existing laptop mode service (if any).'
+-$RCPROG $INITSCRIPT stop
+-
+ INSTALL="install -o root -g root"
+ 
+ mkdir -p /etc/laptop-mode /etc/laptop-mode/batt-start /etc/laptop-mode/batt-stop /etc/laptop-mode/lm-ac-start /etc/laptop-mode/lm-ac-stop /etc/laptop-mode/nolm-ac-start /etc/laptop-mode/nolm-ac-stop /usr/lib/laptop-mode-tools/modules /etc/laptop-mode/conf.d /etc/laptop-mode/modules
+@@ -147,7 +110,6 @@
+ 		echo "$0: Failed to install ACPI event file in /etc/acpi/events. Installation failed."
+ 		exit 14
+ 	fi
+-	killall -HUP acpid
+ 	echo "Installed ACPI support."
+ 	ACPI_DONE=1
+ fi
+@@ -202,31 +164,6 @@
  	echo "Install either acpid, apmd, pbbuttonsd or pmud (depending on what your laptop supports) and reinstall."
  fi
  
@@ -189,9 +207,19 @@ diff -Naur laptop-mode-tools-1.34-orig/install.sh laptop-mode-tools-1.34/install
  if ( ! mkdir -p $MAN_D ) ; then
    echo "$0: Could not create directory $MAN_D. Installation failed."
    exit 22
-diff -Naur laptop-mode-tools-1.34-orig/usr/sbin/laptop_mode laptop-mode-tools-1.34/usr/sbin/laptop_mode
---- laptop-mode-tools-1.34-orig/usr/sbin/laptop_mode	2007-05-28 09:00:15.000000000 -0600
-+++ laptop-mode-tools-1.34/usr/sbin/laptop_mode	2007-10-15 19:09:48.000000000 -0600
+@@ -236,9 +173,4 @@
+   exit 23
+ fi
+ 
+-if ( ! $RCPROG $INITSCRIPT start ) ; then
+-	echo "$0: Could not start laptop mode init script /etc/init.d/laptop-mode."
+-	exit 24
+-fi
+-
+ echo "Installation complete."
+diff -Naur laptop-mode-tools-1.34.orig/usr/sbin/laptop_mode laptop-mode-tools-1.34/usr/sbin/laptop_mode
+--- laptop-mode-tools-1.34.orig/usr/sbin/laptop_mode	2007-05-28 08:00:15.000000000 -0700
++++ laptop-mode-tools-1.34/usr/sbin/laptop_mode	2007-10-17 19:12:24.216585250 -0700
 @@ -374,18 +374,20 @@
  
  #############################################################################
