python: Use make install, otherwise install fails if we've somehow removed/broken python
Without this, python -> python2 and python2 -> python ... so circular links, not sure how.
Use TRACK_INSTALL for symlink targets
Don't try to copy a directory if it doesn't exist.

diff --git a/devel/python/INSTALL b/devel/python/INSTALL
--- a/devel/python/INSTALL
+++ b/devel/python/INSTALL
@@ -1,4 +1,4 @@
-cp -dRv "$SOURCE_DIRECTORY/anywhere/$INSTALL_ROOT/usr" "$INSTALL_ROOT/" &&
+make install DESTDIR="$INSTALL_ROOT" &&
 
 if [[ -f "$SOURCE_DIRECTORY/spell-tmp/pydcop.py" ]]; then
   cp "$SOURCE_DIRECTORY/spell-tmp/pydcop.py" "$PYPATH"
@@ -14,14 +14,14 @@ local PYVER=`echo ${VERSION}|cut -d . -f 1,2` &&
 # symlinks, as they are not created with altinstall.
 # See https://mail.python.org/pipermail/python-dev/2011-March/108971.html
 # and the surrounding thread for fun.
-ln -sf python$PYVER "$INSTALL_ROOT/usr/bin/python"
-ln -sf python$PYVER "$INSTALL_ROOT/usr/bin/python2" &&
-ln -sf python$PYVER-config "$INSTALL_ROOT/usr/bin/python2-config" &&
+ln -sf "${TRACK_ROOT}/usr/bin/python$PYVER" "$INSTALL_ROOT/usr/bin/python" || true # always fails?
+ln -sf "${TRACK_ROOT}/usr/bin/python$PYVER" "$INSTALL_ROOT/usr/bin/python2" &&
+ln -sf "${TRACK_ROOT}/usr/bin/python$PYVER-config" "$INSTALL_ROOT/usr/bin/python2-config" &&
 
 if [ -d "${INSTALL_ROOT}/usr/lib/python${PYVER}/plat-linux2" ];then
    cp -r "${INSTALL_ROOT}/usr/lib/python${PYVER}/plat-linux2" \
    "${INSTALL_ROOT}/usr/lib/python${PYVER}/plat-linux3"
-else
+elif [ -d "${INSTALL_ROOT}/usr/lib/python${PYVER}/plat-linux3" ] ; then
    cp -r "${INSTALL_ROOT}/usr/lib/python${PYVER}/plat-linux3" \
    "${INSTALL_ROOT}/usr/lib/python${PYVER}/plat-linux2"
 fi
